<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'id' => 8,
                'category_id' => 5,
                'books_images' => 'images/books/ErbloJaCrsvs2n4yIpkdZFgRZaK0JuFbRbWR0O5l.jpg',
                'books_author' => 'Sulistyo Basuki',
                'books_name' => 'Pengantar Ilmu Perpustakaan',
                'books_desc' => 'buku ini menjelaskan tentang pengantar ilmu perpustakaan',
                'price' => 70000.00,
                'stock' => 6,
                'created_at' => '2026-04-21 19:30:11',
                'updated_at' => '2026-04-21 19:30:11',
            ],
            [
                'id' => 9,
                'category_id' => 5,
                'books_images' => 'images/books/GwjRFJBWxJqYVSJNSdUEXYlyKE9tVm6JZFrIfeEQ.jpg',
                'books_author' => 'Wiji Suwarno',
                'books_name' => 'Ilmu Perpustakaan & Kode Etik Pustakawan',
                'books_desc' => 'buku ini menjelaskan tentang kode etik pustakawan terhadap pemustaka',
                'price' => 50000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 19:31:24',
                'updated_at' => '2026-04-21 19:31:24',
            ],
            [
                'id' => 10,
                'category_id' => 5,
                'books_images' => 'images/books/zs0coIGtACcBdb13EAXuXzdco8KG3B83OUimGblF.jpg',
                'books_author' => 'Wiji Suwarno',
                'books_name' => 'Dasar-Dasar Ilmu Perpustakaan',
                'books_desc' => 'pengenalan ilmu perpustakaan dan dasar dasar ilmu perpustakaan',
                'price' => 45000.00,
                'stock' => 5,
                'created_at' => '2026-04-21 19:32:24',
                'updated_at' => '2026-04-21 19:32:24',
            ],
            [
                'id' => 11,
                'category_id' => 5,
                'books_images' => 'images/books/zpQyFfwWzG234BSIvEz5MB8cxcj7JqQihFCsdyhl.jpg',
                'books_author' => 'Ericson Marihot Hutapea',
                'books_name' => 'Dasar-Dasar Pengembangan Koleksi di Perpustakaan',
                'books_desc' => 'penjelasan tentang pengembangan koleksi di perpustakaan',
                'price' => 70000.00,
                'stock' => 4,
                'created_at' => '2026-04-21 19:33:37',
                'updated_at' => '2026-04-21 19:33:37',
            ],
            [
                'id' => 12,
                'category_id' => 5,
                'books_images' => 'images/books/8P388H4nkqmxE0eG19hooiMnIOgiywNGmQo2Oove.jpg',
                'books_author' => 'Wiji Suwarno',
                'books_name' => 'Perpustakaan & Buku',
                'books_desc' => 'buku ini menerangkan bagaimana cara pustakawan mengelola perpustakaan dan mengelola buku.',
                'price' => 30000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 19:34:50',
                'updated_at' => '2026-04-21 19:34:50',
            ],
            [
                'id' => 13,
                'category_id' => 5,
                'books_images' => 'images/books/3jZ3UKKzjYIHIsxvu4BpKwF6vqfMG1tmoQ5u1PUu.jpg',
                'books_author' => 'Variant Anna, dkk',
                'books_name' => 'Transformasi Perpustakaan Perguruan Tinggi Indonesia',
                'books_desc' => 'buku ini menjelaskan tentangg transformasi perpustakaan khususnya di perguruan tinggi indonesia',
                'price' => 55000.00,
                'stock' => 7,
                'created_at' => '2026-04-21 19:36:00',
                'updated_at' => '2026-04-21 19:36:00',
            ],
            [
                'id' => 14,
                'category_id' => 5,
                'books_images' => 'images/books/ZmvmQwGgLOcE723YKBuc7FCc75GvNlR554KvFU95.jpg',
                'books_author' => 'Yohanes Edi Purwanto & Herpratiwi',
                'books_name' => 'Perpustakaan Sekolah',
                'books_desc' => 'buku ini menerangkan tentang bagaimana cara mengelola perpustakaan di lembaga pendidikan sekolah',
                'price' => 40000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 19:37:46',
                'updated_at' => '2026-04-21 19:37:46',
            ],
            [
                'id' => 15,
                'category_id' => 5,
                'books_images' => 'images/books/gAdkh7lx1kVNfoUJKjoPexXYJsAQm4ltHzVRzacC.jpg',
                'books_author' => 'DRS, Hartono, SS, M,Hum',
                'books_name' => 'Manajemen Perpustakaan Sekolah',
                'books_desc' => 'buku ini menjelaskan tentang bagaimana perpustakaan sekolah dikelola dengan baik dan benar',
                'price' => 56000.00,
                'stock' => 9,
                'created_at' => '2026-04-21 19:39:08',
                'updated_at' => '2026-04-21 19:39:08',
            ],
            [
                'id' => 16,
                'category_id' => 5,
                'books_images' => 'images/books/JGOgapLmdhvqk3Csb7n6m5c5mBZ8bAGnvIveI9oo.jpg',
                'books_author' => 'Drs, Pawit M. Yusup, M,S',
                'books_name' => 'Ilmu Informasi, Komunikasi, dan Kepustakaan',
                'books_desc' => 'buku tentang informasi komunikasi dan kepustakaan',
                'price' => 70000.00,
                'stock' => 6,
                'created_at' => '2026-04-21 20:31:06',
                'updated_at' => '2026-04-21 20:31:06',
            ],
            [
                'id' => 17,
                'category_id' => 5,
                'books_images' => 'images/books/0TDo8FJqpbrbrOuV5WO0r6f9ptOUHk9rN7fgb1Db.jpg',
                'books_author' => 'Sulistyo Basuki',
                'books_name' => 'Pengantar Ilmu Kearsipan',
                'books_desc' => 'buku ini menjelaskant tentang bagaimana pengantar ilmu kearsipann',
                'price' => 45000.00,
                'stock' => 9,
                'created_at' => '2026-04-21 20:36:14',
                'updated_at' => '2026-04-21 20:36:14',
            ],
            [
                'id' => 18,
                'category_id' => 5,
                'books_images' => 'images/books/B2KgdGiATpg9oZatJbQfowDSeuHFjvsE29PQ6YMx.jpg',
                'books_author' => 'DRS, Hartono, SS, M,Hum',
                'books_name' => 'Manajemen Sumber Informasi Perpustakaan',
                'books_desc' => 'buku ini menjelaskan tentang sumber informasi perpustakaan',
                'price' => 45000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 20:52:50',
                'updated_at' => '2026-04-21 20:52:50',
            ],
            [
                'id' => 19,
                'category_id' => 5,
                'books_images' => 'images/books/qaH8Esd658ESwDAHO7oOc9SMYHPb0968WDRC9I7a.jpg',
                'books_author' => 'Elva Rahmah, S.Sos., M.I.Kom & Testiani Makmur, M.A',
                'books_name' => 'Kebijakan Sumber Informasi Perpustakaan',
                'books_desc' => 'buku ini menjelaskan tentang kebijakan sumber informasi',
                'price' => 55000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 20:54:29',
                'updated_at' => '2026-04-21 20:54:29',
            ],
            [
                'id' => 20,
                'category_id' => 5,
                'books_images' => 'images/books/GN3u5XQGnbB3EkXJtYuecxS7GUJtpW1uEG0k4e9A.jpg',
                'books_author' => 'Prof, Dr, Jannoer, Drs,M.S',
                'books_name' => 'Perpustakaan dan Sains (ilmu) Informasi',
                'books_desc' => 'buku ini menjelaskan bagaimana cara mengelola perpustakaan dan sains ilmu informasi',
                'price' => 43000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 20:56:23',
                'updated_at' => '2026-04-21 20:56:23',
            ],
            [
                'id' => 21,
                'category_id' => 5,
                'books_images' => 'images/books/F2R7jNa9dVVF2D6ZNTksi3846kBEsLGskGoSawrE.jpg',
                'books_author' => 'Dr. Ninis Agustini Damayani, M.I.ib & Dr. H. Edwin Rizal, M,Si',
                'books_name' => 'Filsafat Ilmu Informasi dan Perpustakaan',
                'books_desc' => 'buku ini menjelaskann tentang filsafat ilmu informasi dan perpustakaan',
                'price' => 80000.00,
                'stock' => 9,
                'created_at' => '2026-04-21 20:59:57',
                'updated_at' => '2026-04-21 20:59:57',
            ],
            [
                'id' => 22,
                'category_id' => 5,
                'books_images' => 'images/books/OfrwVzq9pqGHQdWSBYB3v10G9B8Vg4SfT9aektfU.jpg',
                'books_author' => 'Testiani Makmur, S.Sos., M.A.',
                'books_name' => 'Budaya Kerja Pustakawan di Era Digitalisasi',
                'books_desc' => 'buku ini menjelaskan tentang budaya kerja pustakawan yang harus diketahui',
                'price' => 84000.00,
                'stock' => 4,
                'created_at' => '2026-04-21 21:01:06',
                'updated_at' => '2026-04-21 21:01:06',
            ],
            [
                'id' => 23,
                'category_id' => 2,
                'books_images' => 'images/books/tag6YqIkuUImiNeCJOoAStfXOAO2npolWE4IGIVD.jpg',
                'books_author' => 'Laini Taylor',
                'books_name' => 'Strange the Dreamer',
                'books_desc' => 'Di dunia di mana memori manusia dapat diunggah ke dalam arsip digital, Elias bekerja sebagai pembersih "data rusak".',
                'price' => 40000.00,
                'stock' => 14,
                'created_at' => '2026-04-21 21:40:18',
                'updated_at' => '2026-04-21 21:40:18',
            ],
            [
                'id' => 24,
                'category_id' => 2,
                'books_images' => 'images/books/swxetGp7E8KDGRvACyVrpOeJARsyZeWCCvELn8PM.jpg',
                'books_author' => 'Okky Madasary',
                'books_name' => 'Mata di Tanah Melus',
                'books_desc' => 'Rara menghabiskan hari-harinya di sebuah perpustakaan tua yang terancam digusur untuk pembangunan mal.',
                'price' => 40000.00,
                'stock' => 18,
                'created_at' => '2026-04-21 21:41:41',
                'updated_at' => '2026-04-21 21:41:41',
            ],
            [
                'id' => 25,
                'category_id' => 2,
                'books_images' => 'images/books/6IMGgzOLT0DNtrmYdklWs6SVlvJpxE0lOsDHPgFo.jpg',
                'books_author' => 'Jenifer A. Nielsen',
                'books_name' => 'The False Prince',
                'books_desc' => 'Sebuah desa nelayan terpencil didera fenomena aneh: setiap sepuluh tahun membawa pergi satu penduduk tanpa jejak.',
                'price' => 30000.00,
                'stock' => 13,
                'created_at' => '2026-04-21 21:42:57',
                'updated_at' => '2026-04-21 21:42:57',
            ],
            [
                'id' => 26,
                'category_id' => 2,
                'books_images' => 'images/books/ecCwWMQTUq3LAOpOZSEt8FMrXOfzw27MrNikP4vq.jpg',
                'books_author' => 'Nellaneva',
                'books_name' => 'Tujuh  Kelana',
                'books_desc' => 'Di masa depan, setiap bayi yang lahir diberikan chip yang memprediksi tanggal kematian mereka.',
                'price' => 45000.00,
                'stock' => 19,
                'created_at' => '2026-04-21 21:44:21',
                'updated_at' => '2026-04-21 21:44:21',
            ],
            [
                'id' => 27,
                'category_id' => 2,
                'books_images' => 'images/books/JCVZPCMlvtPJlJc57XNX76TVXlrWl9Mw9h2DbIVQ.jpg',
                'books_author' => 'Alexandra Adhornetto',
                'books_name' => 'Hades',
                'books_desc' => 'Sebuah buku tua di perpustakaan kota tidak pernah bisa dibuka selama 50 tahun.',
                'price' => 49000.00,
                'stock' => 15,
                'created_at' => '2026-04-21 21:45:47',
                'updated_at' => '2026-04-21 21:45:47',
            ],
            [
                'id' => 28,
                'category_id' => 2,
                'books_images' => 'images/books/BMgEBTwccR3nLyQbDKzU7Ri53nO8SnFQ0udZkUM4.jpg',
                'books_author' => 'Bex Hogan',
                'books_name' => 'Viper',
                'books_desc' => 'Dua orang asing selalu bertemu di kedai kopi yang sama setiap kali hujan turun, namun mereka tidak pernah berbicara.',
                'price' => 80000.00,
                'stock' => 20,
                'created_at' => '2026-04-21 21:46:52',
                'updated_at' => '2026-04-21 21:46:52',
            ],
            [
                'id' => 29,
                'category_id' => 2,
                'books_images' => 'images/books/CqUpatz0Ch8kAUWWNUcCCpaoInYZDsMYfYoGTEJg.jpg',
                'books_author' => 'S.G Prince',
                'books_name' => 'Elvish',
                'books_desc' => 'Seorang pembunuh bayaran yang sudah pensiun terpaksa kembali beraksi untuk target terakhirnya.',
                'price' => 48000.00,
                'stock' => 9,
                'created_at' => '2026-04-21 21:48:02',
                'updated_at' => '2026-04-21 21:48:02',
            ],
            [
                'id' => 30,
                'category_id' => 2,
                'books_images' => 'images/books/zyggLFtDfnxHyse63ym8TqwKt16vLTXxV3McZ44D.jpg',
                'books_author' => 'Rick Riordan',
                'books_name' => 'The Heroes Of Olympus',
                'books_desc' => 'Di sebuah kerajaan di mana sihir hanya bisa dikeluarkan melalui nyanyian, sang putri lahir tanpa suara.',
                'price' => 50000.00,
                'stock' => 8,
                'created_at' => '2026-04-21 21:49:15',
                'updated_at' => '2026-04-21 21:49:15',
            ],
            [
                'id' => 31,
                'category_id' => 2,
                'books_images' => 'images/books/hRrWJKJraekd2KC0MBYSVxMXxtG4fTivMeLyoOeT.jpg',
                'books_author' => 'Jacey Bedford',
                'books_name' => 'The Amber Crown',
                'books_desc' => 'Di sebuah kerajaan di mana sihir hanya bisa dikeluarkan melalui nyanyian, sang putri lahir tanpa suara.',
                'price' => 70000.00,
                'stock' => 5,
                'created_at' => '2026-04-21 21:52:35',
                'updated_at' => '2026-04-21 21:52:35',
            ],
            [
                'id' => 32,
                'category_id' => 4,
                'books_images' => 'images/books/2LibpCNYbVigXUIUay9K2gchcEYq4n2rdq4owEt4.jpg',
                'books_author' => 'Komarudin Hidayat',
                'books_name' => 'Agama untuk Peradaban',
                'books_desc' => 'Buku ini menawarkan solusi dari sudut pandang Al-Qur\'an dan Sunnah dalam menghadapi problematika hidup.',
                'price' => 45000.00,
                'stock' => 6,
                'created_at' => '2026-04-22 23:29:22',
                'updated_at' => '2026-04-22 23:29:22',
            ],
            [
                'id' => 33,
                'category_id' => 4,
                'books_images' => 'images/books/1o44Z706OndlmGP0WHLHJPrpWYeOgupjGsr7U8Oh.jpg',
                'books_author' => 'Dr. Abdul Wahid, M.A',
                'books_name' => 'Pendidikan Agama Islam',
                'books_desc' => 'Buku panduan ibadah praktis yang membahas hukum-hukum Islam (fiqh) mulai dari thaharah hingga muamalah.',
                'price' => 28000.00,
                'stock' => 4,
                'created_at' => '2026-04-22 23:30:21',
                'updated_at' => '2026-04-22 23:30:21',
            ],
            [
                'id' => 34,
                'category_id' => 4,
                'books_images' => 'images/books/2jK9N9mn6p24yNdJoQeOMGexJLRItcTIswWrtSaW.jpg',
                'books_author' => 'Ali Abdurrahman',
                'books_name' => 'The Sacred Path to Islam',
                'books_desc' => 'Karya ini merupakan panduan untuk menyucikan jiwa (tazkiyatun nafs).',
                'price' => 55000.00,
                'stock' => 9,
                'created_at' => '2026-04-22 23:45:37',
                'updated_at' => '2026-04-22 23:45:37',
            ],
            [
                'id' => 35,
                'category_id' => 4,
                'books_images' => 'images/books/jGUlVrLysimkK9Hkko1VTqiMapfWTmsjY5yNdtsR.jpg',
                'books_author' => 'Dr. Muhammad Iqbal Irham M.Ag.',
                'books_name' => 'Pengembangan Karakter Islam',
                'books_desc' => 'Tafsir Al-Qur\'an yang khas dengan pendekatan sastra dan budaya Nusantara.',
                'price' => 35000.00,
                'stock' => 9,
                'created_at' => '2026-04-22 23:47:04',
                'updated_at' => '2026-04-22 23:47:04',
            ],
            [
                'id' => 36,
                'category_id' => 3,
                'books_images' => 'images/books/afNdsnIy7T93NpG4BCk0MPFoEBCnhTFzODjU0gRo.jpg',
                'books_author' => 'Sri Wahyuni, S.Kom',
                'books_name' => 'Sistem Basis Data',
                'books_desc' => 'buku ini menjelaskan tentang basis data, bagaimana data itu dibuat dan dijalankann',
                'price' => 40000.00,
                'stock' => 9,
                'created_at' => '2026-04-22 23:48:48',
                'updated_at' => '2026-04-22 23:48:48',
            ],
            [
                'id' => 37,
                'category_id' => 3,
                'books_images' => 'images/books/sUIBPawF3Jdq7kLv3IjOwnojlnyDCtKRYxfI8w4k.jpg',
                'books_author' => 'Agnes Novita Ida, S.Kom',
                'books_name' => 'Sistem Basis Data',
                'books_desc' => 'buku ini menjelaskan tentang php mysql',
                'price' => 40000.00,
                'stock' => 9,
                'created_at' => '2026-04-23 00:23:35',
                'updated_at' => '2026-04-23 00:23:35',
            ],
        ]);
    }
}
